In [1]:
import pandas as pd
ipums_path = "nhis_00001.csv.gz"

In [2]:
df = pd.read_csv(ipums_path, low_memory=False)

df.head(3)

,YEAR,SERIAL,STRATA,PSU,NHISHID,PERNUM,NHISPID,HHX,SAMPWEIGHT,LONGWEIGHT,...,HEIGHT,WEIGHT,BMICALC,HINOTCOVE,HIPRIVATEE,HISTATEE,PCEMAILHPYR,PCACS,CVDDIAG,CVDTEST
0,2020,1,150,25,0002020H000002,1,0002020H00000210,H000002,5946.002,17605.5,...,66,230,37.1,1,2,10,NaN,NaN,1.0,1.0
1,2020,2,111,10,0002020H000003,1,0002020H00000310,H000003,6288.726,0.0,...,71,180,25.1,1,2,10,NaN,NaN,0.0,0.0
2,2020,3,133,3,0002020H000004,1,0002020H00000410,H000004,6083.271,0.0,...,64,155,26.6,1,2,10,NaN,NaN,0.0,0.0

In [9]:
rename_columns = {
    # 
    "YEAR": "year",
    "SERIAL": "serial_number",
    "STRATA": "sampling_strata",
    "PSU": "primary_sampling_unit",
    "NHISHID": "household_id",
    "PERNUM": "person_number",
    "NHISPID": "person_id",
    "HHX": "household_number",
    "RECTYPE": "record_type",         
    "ASTATFLG": "sample_adult_flag",   
    "CSTATFLG": "sample_child_flag",   
    # weights
    "SAMPWEIGHT": "sample_person_weight",
    "LONGWEIGHT": "longitudinal_weight",

    # demographics
    "SEX": "sex",
    "RACENEW": "race",
    "LANGHOMEOT": "non_english_at_home",

    # education
    "EDUC": "education_attainment",
    "MAXEDUC": "max_education_in_family",

    # health status 
    "HEALTH": "health_status",
    "HEIGHT": "height_inches",
    "WEIGHT": "weight_pounds",
    "BMICALC": "bmi",

    # insurance / access
    "HINOTCOVE": "health_insurance_coverage",
    "HIPRIVATEE": "private_insurance_coverage",
    "HISTATEE": "state_plan_insurance_coverage",
    "PCEMAILHPYR": "emailed_provider_past_12mo",
    "PCACS": "internet_access",

    # covid
    "CVDDIAG": "covid19_diagnosed_flag",
    "CVDTEST": "covid19_tested_flag",
}

In [10]:
df.rename(columns=rename_columns, inplace=True)

In [12]:
df.head(10)

,year,serial_number,sampling_strata,primary_sampling_unit,household_id,person_number,person_id,household_serial,sample_weight,longitudinal_weight,...,height_inches_no_shoes,weight_pounds,bmi,no_health_insurance_flag,private_insurance_flag,state_plan_insurance_flag,emailed_provider_past_12mo,internet_access_flag,covid19_diagnosed_flag,covid19_tested_flag
0,2020,1,150,25,0002020H000002,1,0002020H00000210,H000002,5946.002,17605.50,...,66,230,37.1,1,2,10,NaN,NaN,1.0,1.0
1,2020,2,111,10,0002020H000003,1,0002020H00000310,H000003,6288.726,0.00,...,71,180,25.1,1,2,10,NaN,NaN,0.0,0.0
2,2020,3,133,3,0002020H000004,1,0002020H00000410,H000004,6083.271,0.00,...,64,155,26.6,1,2,10,NaN,NaN,0.0,0.0
3,2020,4,139,45,0002020H000007,1,0002020H00000710,H000007,11306.962,0.00,...,67,240,37.6,1,2,10,NaN,NaN,0.0,0.0
4,2020,5,130,21,0002020H000009,1,0002020H00000910,H000009,6471.818,19317.18,...,66,180,29.0,2,1,10,NaN,NaN,1.0,1.0
5,2020,6,131,2,0002020H000011,1,0002020H00001110,H000011,3121.049,13087.37,...,96,996,996.0,1,2,10,NaN,NaN,1.0,1.0
6,2020,7,128,27,0002020H000014,1,0002020H00001410,H000014,754.476,0.00,...,68,160,24.3,1,2,10,NaN,NaN,1.0,1.0
7,2020,8,123,22,0002020H000018,1,0002020H00001810,H000018,5120.231,0.00,...,64,160,27.5,1,1,10,NaN,NaN,0.0,0.0
8,2020,9,122,11,0002020H000019,1,0002020H00001910,H000019,2682.171,0.00,...,64,160,27.5,2,1,10,NaN,NaN,1.0,2.0
9,2020,10,149,18,0002020H000022,1,0002020H00002210,H000022,1738.221,16060.22,...,67,155,24.3,1,2,10,NaN,NaN,1.0,1.0

In [11]:
print(df.columns)

Index(['year', 'serial_number', 'sampling_strata', 'primary_sampling_unit',
       'household_id', 'person_number', 'person_id', 'household_serial',
       'sample_weight', 'longitudinal_weight', 'PARTWEIGHT',
       'sample_adult_flag', 'sample_child_flag', 'AGE', 'sex',
       'race_omb_recode', 'non_english_at_home_flag', 'education_attainment',
       'max_education_in_family', 'self_rated_health',
       'height_inches_no_shoes', 'weight_pounds', 'bmi',
       'no_health_insurance_flag', 'private_insurance_flag',
       'state_plan_insurance_flag', 'emailed_provider_past_12mo',
       'internet_access_flag', 'covid19_diagnosed_flag',
       'covid19_tested_flag'],
      dtype='object')

In [13]:
df.head(10)

,year,serial_number,sampling_strata,primary_sampling_unit,household_id,person_number,person_id,household_serial,sample_weight,longitudinal_weight,...,height_inches_no_shoes,weight_pounds,bmi,no_health_insurance_flag,private_insurance_flag,state_plan_insurance_flag,emailed_provider_past_12mo,internet_access_flag,covid19_diagnosed_flag,covid19_tested_flag
0,2020,1,150,25,0002020H000002,1,0002020H00000210,H000002,5946.002,17605.50,...,66,230,37.1,1,2,10,NaN,NaN,1.0,1.0
1,2020,2,111,10,0002020H000003,1,0002020H00000310,H000003,6288.726,0.00,...,71,180,25.1,1,2,10,NaN,NaN,0.0,0.0
2,2020,3,133,3,0002020H000004,1,0002020H00000410,H000004,6083.271,0.00,...,64,155,26.6,1,2,10,NaN,NaN,0.0,0.0
3,2020,4,139,45,0002020H000007,1,0002020H00000710,H000007,11306.962,0.00,...,67,240,37.6,1,2,10,NaN,NaN,0.0,0.0
4,2020,5,130,21,0002020H000009,1,0002020H00000910,H000009,6471.818,19317.18,...,66,180,29.0,2,1,10,NaN,NaN,1.0,1.0
5,2020,6,131,2,0002020H000011,1,0002020H00001110,H000011,3121.049,13087.37,...,96,996,996.0,1,2,10,NaN,NaN,1.0,1.0
6,2020,7,128,27,0002020H000014,1,0002020H00001410,H000014,754.476,0.00,...,68,160,24.3,1,2,10,NaN,NaN,1.0,1.0
7,2020,8,123,22,0002020H000018,1,0002020H00001810,H000018,5120.231,0.00,...,64,160,27.5,1,1,10,NaN,NaN,0.0,0.0
8,2020,9,122,11,0002020H000019,1,0002020H00001910,H000019,2682.171,0.00,...,64,160,27.5,2,1,10,NaN,NaN,1.0,2.0
9,2020,10,149,18,0002020H000022,1,0002020H00002210,H000022,1738.221,16060.22,...,67,155,24.3,1,2,10,NaN,NaN,1.0,1.0

In [16]:
import pandas as pd
import numpy as np

In [19]:
# use partial/sample-adult if present...if not use the general weight
weight_col = "partial_sample_weight" if "partial_sample_weight" in df.columns else "sample_weight"

In [20]:
#Categorize labels

In [21]:
if "race_omb_recode" in df.columns:
    race_labels = {
        100: "White", 200: "Black", 300: "AIAN", 400: "Asian",
        510: "Other/Multiracial", 520: "Other", 541: "Multiracial",
        997: "Unknown-Refused", 998: "Unknown-NA", 999: "Unknown-DK"
    }

In [24]:
   df["race_grp"] = df["race_omb_recode"].map(race_labels).fillna("Other/Unknown")

KeyError: 'race_omb_recode'

In [15]:
csv_path = "adult24.csv"  
df = pd.read_csv(csv_path, low_memory=False)

print(df.head())

   RATCAT_A  INCTCFLG_A  IMPINCFLG_A  PPSU  PSTRAT  WLKLEISTC_A  WLKTRANTC_A  \
0         9           0            2     2     122          NaN          NaN
1         8           0            0     2     122         20.0          NaN
2         7           0            0     2     122         30.0          NaN
3        12           0            0     2     122         10.0          NaN
4        14           0            0     1     115          NaN          NaN

   HISPALLP_A  RACEALLP_A  ANYDIFF_A  ...  LSATIS4_A  PHSTAT_A  HHSTAT_A  \
0           2           1          2  ...          1         1         1
1           2           1          2  ...          2         2         1
2           2           1          1  ...          1         2         1
3           2           1          1  ...          2         3         1
4           3           2          1  ...          2         3         1

   INTV_MON  RECTYPE  IMPNUM_A  AVGNUMCIG_A     WTFA_A      HHX  POVRATTC_A
0         1       10         1           30   5780.565  H067658        2.82
1         1       10         1           20   3994.244  H076577        2.01
2         1       10         1           20   6636.755  H019335        1.90
3         1       10         1           01  13767.420  H012701        4.48
4         1       10         1          NaN  18880.030  H049678        6.37

[5 rows x 630 columns]